### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by FindHao** [pytorch/benchmark#1282]
### PyTorch Version:
nightly torch-1.14.0.dev20221104%2Bcu116-cp38-cp38-linux_x86_64.whl
### Error 
```
from torch.testing import assert_allclose as _assert_close
ImportError: cannot import name 'assert_allclose' from 'torch.testing' 
(miniconda3/envs/pt_nov4/lib/python3.8/site-packages/torch/testing/__init__.py)
```
Error occurs when install DALLE2_pytorch. It is related to this issue https://github.com/pytorch/pytorch/issues/61844

It looks like the nightly version deprecated some functions.

**Comment by FindHao** [comment]
Full error stack:
```
Traceback (most recent call last):
  File "install.py", line 20, in <module>
    patch_dalle2()
  File "install.py", line 7, in patch_dalle2
    import dalle2_pytorch
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/dalle2_pytorch/__init__.py", line 2, in <module>
    from dalle2_pytorch.dalle2_pytorch import DALLE2, DiffusionPriorNetwork, DiffusionPrior, Unet, Decoder
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/dalle2_pytorch/dalle2_pytorch.py", line 20, in <module>
    from kornia.filters import gaussian_blur2d
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/kornia/__init__.py", line 3, in <module>
    from . import filters
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/kornia/filters/__init__.py", line 2, in <module>
    from .blur_pool import BlurPool2D, MaxBlurPool2D, blur_pool2d, edge_aware_blur_pool2d, max_blur_pool2d
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/kornia/filters/blur_pool.py", line 7, in <module>
    from kornia.testing import KORNIA_CHECK, KORNIA_CHECK_SHAPE
  File "/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/kornia/testing/__init__.py", line 254, in <module>
    from torch.testing import assert_allclose as _assert_close
ImportError: cannot import name 'assert_allclose' from 'torch.testing' (/home/ubuntu/miniconda3/envs/pt_nov4/lib/python3.8/site-packages/torch/testing/__init__.py)
```

**Comment by xuzhao9** [comment]
This is because upstream issue: https://github.com/kornia/kornia/issues/1981, we will update after upstream fixes

**Comment by xuzhao9** [comment]
Fixed
