### ISSUE TITLE
E2E model running bug 

### ISSUE THREAD

**Issue by yanboliang** [pytorch/benchmark#1289]
Run:
```
python run_e2e.py hf_bert -t eval
```
Error:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/benchmark/run_e2e.py", line 43, in <module>
    m = Model(test=args.test, batch_size=[args.bs](http://args.bs/), extra_args=extra_args)
  File "/scratch/ybliang/work/repos/benchmark/torchbenchmark/util/e2emodel.py", line 8, in _call_
    obj = type.__call__(cls, *args, **kwargs)
  File "/scratch/ybliang/work/repos/benchmark/torchbenchmark/e2e_models/hf_bert/__init__.py", line 83, in _init_
    self.prep(hf_args)
  File "/scratch/ybliang/work/repos/benchmark/torchbenchmark/e2e_models/hf_bert/__init__.py", line 132, in prep
    model = DDP(
  File "/scratch/ybliang/work/repos/pytorch/torch/nn/parallel/distributed.py", line 616, in _init_
    self.process_group = _get_default_group()
  File "/scratch/ybliang/work/repos/pytorch/torch/distributed/distributed_c10d.py", line 588, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Comment by xuzhao9** [comment]
Fixed in https://github.com/pytorch/benchmark/pull/1291
