### ISSUE TITLE
Simple PytorchBenchmark script gives CUDA forked subprocess error

### ISSUE THREAD

**Issue by ClaartjeBarkhof** [pytorch/benchmark#141]
When I try to run a simple Pytorch Benchmark test I get this error:

```
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Traceback (most recent call last):
  File "/home/cbarkhof/code-thesis/Experimentation/Benchmarking/benchmarking-models-claartje.py", line 31, in <module>
    benchmark.run()
  File "/home/cbarkhof/.local/lib/python3.6/site-packages/transformers/benchmark/benchmark_utils.py", line 674, in run
    memory, inference_summary = self.inference_memory(model_name, batch_size, sequence_length)
ValueError: too many values to unpack (expected 2)
```

The script is as simple as this:
```
from transformers import PyTorchBenchmark, PyTorchBenchmarkArguments

benchmark_args = PyTorchBenchmarkArguments(models=["bert-base-uncased"],
                                           batch_sizes=[8],
                                           sequence_lengths=[8, 32, 128, 512],
                                           save_to_csv=True,
                                           log_filename='log',
                                           env_info_csv_file='env_info')

benchmark = PyTorchBenchmark(benchmark_args)
benchmark.run()
```

**Comment by ClaartjeBarkhof** [comment]
This happens on my machine, but also in this notebook running on Colab: https://github.com/huggingface/transformers/blob/master/notebooks/05-benchmark.ipynb

**Comment by xuzhao9** [comment]
Closed, this is not relevant anymore.
