### ISSUE TITLE
python install.py fails on Windows 10 Python 3.7.9 

### ISSUE THREAD

**Issue by sbocconi** [pytorch/benchmark#149]
python install fails with `OSError: [Errno 22] Invalid argument: 'M:\\AI\\benchmark\\myenvW\\lib\\site-packages\\wincertstore-0.2-py3.7.egg-info\\entry_points.txt'`

while installing in virtual environment (myenvW) created with conda 4.9.1 (miniconda).
wincertstore does not have an entry_points.txt, and the package seems not to be updated anymore.

Complete traceback:
```
Traceback (most recent call last):
  File "M:\AI\benchmark\myenvW\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "M:\AI\benchmark\myenvW\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "M:\AI\benchmark\myenvW\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "M:\AI\benchmark\myenvW\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "M:\AI\benchmark\myenvW\lib\site-packages\thinc\__init__.py", line 8, in <module>
    from ._registry import registry
  File "M:\AI\benchmark\myenvW\lib\site-packages\thinc\_registry.py", line 1, in <module>
    import catalogue
  File "M:\AI\benchmark\myenvW\lib\site-packages\catalogue.py", line 18, in <module>
    AVAILABLE_ENTRY_POINTS = importlib_metadata.entry_points()
  File "M:\AI\benchmark\myenvW\lib\site-packages\importlib_metadata\__init__.py", line 596, in entry_points
    ordered = sorted(eps, key=by_group)
  File "M:\AI\benchmark\myenvW\lib\site-packages\importlib_metadata\__init__.py", line 594, in <genexpr>
    dist.entry_points for dist in distributions())
  File "M:\AI\benchmark\myenvW\lib\site-packages\importlib_metadata\__init__.py", line 289, in entry_points
    return EntryPoint._from_text(self.read_text('entry_points.txt'))
  File "M:\AI\benchmark\myenvW\lib\site-packages\importlib_metadata\__init__.py", line 545, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "M:\AI\benchmark\myenvW\lib\pathlib.py", line 1221, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "M:\AI\benchmark\myenvW\lib\pathlib.py", line 1208, in open
    opener=self._opener)
  File "M:\AI\benchmark\myenvW\lib\pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 22] Invalid argument: 'M:\\AI\\benchmark\\myenvW\\lib\\site-packages\\wincertstore-0.2-py3.7.egg-info\\entry_points.txt'
Traceback (most recent call last):
  File "install.py", line 16, in <module>
    spacy_download('en')
  File "install.py", line 9, in spacy_download
    subprocess.check_call([sys.executable, '-m', 'spacy', 'download', language])
  File "M:\AI\benchmark\myenvW\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['M:\\AI\\benchmark\\myenvW\\python.exe', '-m', 'spacy', 'download', 'en']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "install.py", line 12, in <module>
    setup()
  File "M:\AI\benchmark\torchbenchmark\__init__.py", line 44, in setup
    _install_deps(model_path)
  File "M:\AI\benchmark\torchbenchmark\__init__.py", line 28, in _install_deps
    subprocess.check_call([sys.executable, install_file], cwd=model_path)
  File "M:\AI\benchmark\myenvW\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['M:\\AI\\benchmark\\myenvW\\python.exe', 'install.py']' returned non-zero exit status 1.
'''

**Comment by xuzhao9** [comment]
Python 3.7 has been deprecated. Closing this issue.
