### ISSUE TITLE
what means AssertionError: Canary model  not found in the canary_models path

### ISSUE THREAD

**Issue by joepareti54** [pytorch/benchmark#1597]
When doing

`python run.py "$name" -d cuda -t train
`
there are exceptions as:
e.g.

AssertionError: Canary model pytorch_CycleGAN_and_pix2pix is not found in the canary_models path

**Comment by joepareti54** [comment]
to be checked. However, on another system the issue does not occur. Apology for the confusion

**Comment by xuzhao9** [comment]
This means a dependency is missing for model pytorch_CycleGAN_and_pix2pix. Can you help post the full error log?

**Comment by joepareti54** [comment]
```
python run.py pytorch_CycleGAN_and_pix2pix -d cuda -t train
Warning: Could not find dependent module dominate for Model pytorch_CycleGAN_and_pix2pix, skip it. 
 No module named 'dominate'
Traceback (most recent call last):
  File "/media/joepareti54/Elements/x/finance-2023/AI/pytorch-AWS_benchmarks/LOCAL_test5/benchmark/run.py", line 301, in <module>
    Model = load_canary_model_by_name(args.model)
  File "/media/joepareti54/Elements/x/finance-2023/AI/pytorch-AWS_benchmarks/LOCAL_test5/benchmark/torchbenchmark/__init__.py", line 604, in load_canary_model_by_name
    assert _is_canary_model(model), f"Canary model {model} is not found in the {canary_model_dir} path."
AssertionError: Canary model pytorch_CycleGAN_and_pix2pix is not found in the canary_models path.
```

**Comment by xuzhao9** [comment]
So the actual error message is ` No module named 'dominate'`
