### ISSUE TITLE
Permission Issue with installation.

### ISSUE THREAD

**Issue by pranavsharma** [pytorch/benchmark#1983]
(python310) C:\Users\prs\work_projects\pytorch_benchmark>python install.py models phi_1_5
checking packages torch, torchvision, torchaudio are installed...OK
running setup for C:\Users\prs\work_projects\pytorch_benchmark\torchbenchmark\models\phi_1_5...Traceback (most recent call last):
  File "C:\Users\prs\work_projects\pytorch_benchmark\install.py", line 60, in <module>
    success &= setup(models=args.models, verbose=args.verbose, continue_on_fail=args.continue_on_fail, test_mode=args.test_mode, allow_canary=args.canary)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prs\work_projects\pytorch_benchmark\torchbenchmark\__init__.py", line 153, in setup
    success, errmsg, stdout_stderr = _install_deps(model_path, verbose=verbose)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prs\work_projects\pytorch_benchmark\torchbenchmark\__init__.py", line 99, in _install_deps
    os.remove(stdout_fpath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\prs\\AppData\\Local\\Temp\\tmpu2dkrtmn'

**Comment by xuzhao9** [comment]
Sorry we don't have Windows environment to test the installation. The benchmark suite assumes Linux only, and support on Windows/MacOS is maintained by the community.

**Comment by pranavsharma** [comment]
Yes, I was able to get past this on Linux. There's some issue on Windows that needs to be debugged. I'll keep this open for now.
