### ISSUE TITLE
Installing benchmarks fails with libtorchaudio.so underfined symbol error

### ISSUE THREAD

**Issue by paolotricerri** [pytorch/benchmark#2021]
HI all, 

I have tried to install the benchmarks in a python environment where I have the following packages:

 - torch 2.1.0
 - torchxla 2.1.0
 - torchvision 0.16.0
 - torchdata 0.7.0
 - torchtext 0.16.0
 - torchaudio 2.1.0

and when installing the benchmarks I get the following error:

(python3-venv) aarch64_pytorch benchmark> python install.py 
checking packages torch, torchvision, torchaudio are installed...Traceback (most recent call last):
  File "/home/ubuntu/benchmark/install.py", line 39, in <module>
    versions = get_pkg_versions(TORCH_DEPS)
  File "/home/ubuntu/benchmark/utils/__init__.py", line 28, in get_pkg_versions
    module = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/python3-venv/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv

Any suggestion on what could be wrong? 
Thanks

**Comment by paolotricerri** [comment]
I have been able to pass the error above by installing torchaudio from sources in my docker image. The install.py script has passed the checks for torch, torchvision, torchaudio and it's setting up the benchmarks.

**Comment by xuzhao9** [comment]
We only test the compatibility of pytorch/torchvision/torchaudio nightly releases. Please try it on the nightly releases.
Currently, we do not check if torchbenchmark runs on stable releases.
