### ISSUE TITLE
ModuleNotFoundError: No module named 'caffe2'

### ISSUE THREAD

**Issue by AidanGoldfarb** [pytorch/benchmark#2066]
To reproduce:

`pip install --pre torch torchvision torchaudio -i https://download.pytorch.org/whl/nightly/cu118`

`git clone https://github.com/pytorch/benchmark
cd benchmark
python install.py`

As per README

and then
`python run_benchmark.py dynamo`

Platform: Ubuntu 20.04.6 LTS
Python: 3.8.10
Torch: 2.1.1

Full error:

Failed to import user benchmark module dynamo, error: No module named 'caffe2'
Traceback (most recent call last):
  File "/data/agoldf6/benchmark/userbenchmark/dynamo/dynamobench/torchbench.py", line 14, in <module>
    from .common import BenchmarkRunner, main
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/agoldf6/benchmark/userbenchmark/dynamo/run.py", line 11, in <module>
    from torchbench import setup_torchbench_cwd, TorchBenchmarkRunner
  File "/data/agoldf6/benchmark/userbenchmark/dynamo/dynamobench/torchbench.py", line 16, in <module>
    from common import BenchmarkRunner, main
  File "/data/agoldf6/benchmark/userbenchmark/dynamo/dynamobench/common.py", line 58, in <module>
    from torch._dynamo.testing import (
ImportError: cannot import name 'reset_rng_state' from 'torch._dynamo.testing' (/data/agoldf6/mypy/lib/python3.8/site-packages/torch/_dynamo/testing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_benchmark.py", line 29, in run
    benchmark = importlib.import_module(f"userbenchmark.{available_benchmarks[args.bm_name]}.run")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/agoldf6/benchmark/userbenchmark/dynamo/run.py", line 15, in <module>
    from caffe2.benchmarks.dynamo.torchbench import setup_torchbench_cwd, TorchBenchmarkRunner
ModuleNotFoundError: No module named 'caffe2'

**Comment by xuzhao9** [comment]
Hi @AidanGoldfarb , could you please try on the torch nightly release? Torchbench relies on the pytorch nightly build, and we do not test on the stable release.

**Comment by AidanGoldfarb** [comment]
Ah this was it. I thought I was running on nightly (from install command from readme), but I reinstalled and it worked, thanks!
