### ISSUE TITLE
CI Failure because of sam_fast CUDA mem leak

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/benchmark#2231]
Failed workflow: https://github.com/pytorch/benchmark/actions/runs/8662210535/job/23753705235

Running bisection: https://github.com/pytorch/benchmark/actions/runs/8662953920

```
======================================================================
FAIL: test_sam_fast_eval_cuda (__main__.TestBenchmark.test_sam_fast_eval_cuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/_work/benchmark/benchmark/test.py", line 115, in eval_fn
    with task.watch_cuda_memory(
  File "/home/runner/miniconda3/envs/pr-ci-a100/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/runner/_work/benchmark/benchmark/torchbenchmark/__init__.py", line 625, in watch_cuda_memory
    assert_equal(
AssertionError: 0 != 12288

----------------------------------------------------------------------
Ran 800 tests in 6516.228s

FAILED (failures=1, skipped=205)
```

**Comment by xuzhao9** [comment]
```
{
  "target_repo": "pytorch",
  "start": "d8e0c26e642bf8e44cc6e8d46822d54957b1c660",
  "start_version": "2.4.0.dev20240411+cu121",
  "end": "65710d95c9adcc166e4d4a19ac16b8d7516fc87b",
  "end_version": "2.4.0.dev20240411+cu121",
  "result": [
    {
      "commit1": "f772ea5493a",
      "commit1_time": "2024-04-09 19:39:31 +0000",
      "commit1_digest": {
        "name": "test_bench",
        "environ": {
          "pytorch_git_version": "f772ea5493a829cdd7f8c0b53f2a8f15a18a06ff",
          "pytorch_version": "2.4.0a0+gitf772ea5",
          "device": "NVIDIA A100-SXM4-40GB",
          "git_commit_hash": "f772ea5493a829cdd7f8c0b53f2a8f15a18a06ff"
        },
        "metrics": {
          "model=sam_fast, test=eval, device=cuda, bs=None, extra_args=['--memleak'], metric=memleak": "False"
        }
      },
      "commit2": "4044e93a51e",
      "commit2_time": "2024-04-09 19:42:19 +0000",
      "commit2_digest": {
        "name": "test_bench",
        "environ": {
          "pytorch_git_version": "4044e93a51e9238de3049a39e203688809df9bc5",
          "pytorch_version": "2.4.0a0+git4044e93",
          "device": "NVIDIA A100-SXM4-40GB",
          "git_commit_hash": "4044e93a51e9238de3049a39e203688809df9bc5"
        },
        "metrics": {
          "model=sam_fast, test=eval, device=cuda, bs=None, extra_args=['--memleak'], metric=memleak": "True"
        }
      }
    }
  ]
}
```

**Comment by xuzhao9** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/124345
