### ISSUE TITLE
hf_T5_generate eager run failed with transformers>=4.41.0

### ISSUE THREAD

**Issue by yiming0416** [pytorch/benchmark#2447]
Starting from `transformers==4.41.0`. It uses `torch.isin()` which prevents graph break in certain control flows. However, when I update the `transformers` package to `>=4.41.0`. I got the error when running with the following command. `transformers<4.41.0` does not have this error.

**Repro**
```python
python benchmarks/dynamo/torchbench.py --accuracy --inference --bfloat16 --device cuda --only=hf_T5_generate
```

**Error log**
```
loading model: 0it [00:15, ?it/s]
cuda eval  hf_T5_generate                     
Traceback (most recent call last):
  File "/home/yimingzhou/pytorch/benchmarks/dynamo/common.py", line 2507, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/home/yimingzhou/pytorch/benchmarks/dynamo/torchbench.py", line 434, in forward_pass
    return mod(*inputs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yimingzhou/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yimingzhou/torchbenchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 188, in forward
    return self.model.generate(inputs, self.generation_config)
  File "/home/yimingzhou/pytorch/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/yimingzhou/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 1543, in generate
    self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
  File "/home/yimingzhou/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 1403, in _prepare_special_tokens
    raise ValueError(
ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/yimingzhou/pytorch/benchmarks/dynamo/common.py", line 4607, in run
    ) = runner.load_model(
  File "/home/yimingzhou/pytorch/benchmarks/dynamo/torchbench.py", line 362, in load_model
    self.validate_model(model, example_inputs)
  File "/home/yimingzhou/pytorch/benchmarks/dynamo/common.py", line 2509, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed
eager_fail_to_run
```

**Python environment:**
```
Package                            Version            Editable project location
---------------------------------- ------------------ ------------------------------------------------------------------
absl-py                            2.1.0
accelerate                         0.33.0
aiohappyeyeballs                   2.4.0
aiohttp                            3.10.5
aiosignal                          1.3.1
annotated-types                    0.7.0
antlr4-python3-runtime             4.9.3
anyascii                           0.3.2
astor                              0.8.1
astroid                            3.2.4
astunparse                         1.6.3
async-timeout                      4.0.3
attrs                              23.1.0
audioread                          3.0.1
autocommand                        2.2.2
babel                              2.16.0
backports.tarfile                  1.2.0
beautifulsoup4                     4.12.3
bert_pytorch                       0.0.1a4            /home/yimingzhou/torchbenchmark/torchbenchmark/models/BERT_pytorch
bibtexparser                       2.0.0b7
black                              23.12.1
blinker                            1.8.2
blis                               0.7.11
blobfile                           2.1.1
bokeh                              3.5.1
boto3                              1.35.3
botocore                           1.35.3
Brotli                             1.0.9
bs4                                0.0.2
build                              1.2.1
cardboardlint                      1.3.1
catalogue                          2.0.10
certifi                            2024.7.4
cffi                               1.16.0
charset-normalizer                 3.3.2
click                              8.1.7
clldutils                          3.22.2
cloudpathlib                       0.18.1
cloudpickle                        3.0.0
cmake                              3.30.2
cmakelint                          1.4.1
colorama                           0.4.6
colorlog                           6.8.2
commonmark                         0.9.1
confection                         0.1.5
contourpy                          1.2.1
csvw                               3.3.0
cycler                             0.12.1
cymem                              2.0.8
Cython                             3.0.10
DALL-E                             0.1
datasets                           2.21.0
decorator                          5.1.1
defusedxml                         0.7.1
detectron2                         0.6
diffusers                          0.20.2
dill                               0.3.8
diskcache                          5.6.3
distro                             1.9.0
dlinfo                             1.2.1
docker-pycreds                     0.4.0
dominate                           2.9.1
effdet                             0.4.1
einops                             0.8.0
exceptiongroup                     1.2.2
expecttest                         0.1.6
FastNLP                            0.6.0
fbgemm_gpu                         0.8.0
ffmpeg-python                      0.2.0
filelock                           3.13.1
flake8                             6.1.0
flake8-bugbear                     23.3.23
flake8-comprehensions              3.15.0
flake8-executable                  2.1.3
flake8-logging-format              0.9.0
flake8-pyi                         23.3.1
flake8-simplify                    0.19.3
Flask                              3.0.3
fonttools                          4.53.1
frozenlist                         1.4.1
fsspec                             2024.6.1
ftfy                               6.2.3
functorch                          1.14.0a0+b71aa0b
future                             0.18.3
fvcore                             0.1.5.post20221221
gdown                              5.2.0
gitdb                              4.0.11
GitPython                          3.1.43
grpcio                             1.66.0rc5
gym                                0.26.2
gym-notices                        0.0.8
h5py                               3.11.0
higher                             0.2.1
huggingface-hub                    0.24.6
hydra-core                         1.3.0
hypothesis                         6.111.1
idna                               3.7
imageio                            2.35.1
importlib_metadata                 8.4.0
importlib_resources                6.4.0
inflect                            7.3.1
iniconfig                          2.0.0
iopath                             0.1.9
isodate                            0.6.1
isort                              5.13.2
itsdangerous                       2.2.0
jaraco.context                     5.3.0
jaraco.functools                   4.0.1
jaraco.text                        3.12.1
Jinja2                             3.1.4
jmespath                           1.0.1
joblib                             1.4.2
jsonpatch                          1.33
jsonpointer                        3.0.0
jsonschema                         4.23.0
jsonschema-specifications          2023.12.1
junitparser                        2.1.1
kaldi-io                           0.9.8
kiwisolver                         1.4.5
kornia                             0.7.3
kornia_rs                          0.1.5
lameenc                            1.7.0
langcodes                          3.4.0
langdetect                         1.0.9
language_data                      1.2.0
language-tags                      1.2.0
lazy_loader                        0.4
libcst                             1.1.0
librosa                            0.10.2.post1
lightning-utilities                0.11.6
lintrunner                         0.12.5
llvmlite                           0.43.0
lxml                               4.9.4
marisa-trie                        1.2.0
Markdown                           3.7
markdown-it-py                     3.0.0
MarkupSafe                         2.1.5
matplotlib                         3.9.2
mccabe                             0.7.0
mdurl                              0.1.2
mkl-fft                            1.3.8
mkl-random                         1.2.4
mkl-service                        2.4.0
MonkeyType                         23.3.0
more-itertools                     10.3.0
moreorless                         0.4.0
mpmath                             1.3.0
msgpack                            1.0.8
multidict                          6.0.5
multiprocess                       0.70.16
munkres                            1.1.4
murmurhash                         1.0.10
musdb                              0.4.2
museval                            0.4.1
mypy                               1.10.0
mypy-extensions                    1.0.0
networkx                           3.3
ninja                              1.11.1.1
nose                               1.3.7
numba                              0.60.0
numpy                              1.26.0
omegaconf                          2.3.0
onnx                               1.16.2
opacus                             1.5.2
opencv-python                      4.10.0.84
opt-einsum                         3.3.0
optree                             0.12.1
ordered-set                        4.1.0
packaging                          24.1
pandas                             2.2.2
patch                              1.16
pathspec                           0.12.1
phonemizer                         3.3.0
pillow                             10.4.0
pip                                24.2
platformdirs                       4.2.2
pluggy                             1.5.0
pooch                              1.8.2
portalocker                        2.10.1
preshed                            3.0.9
prettytable                        3.11.0
protobuf                           4.25.3
psutil                             6.0.0
py-cpuinfo                         9.0.0
pyaml                              24.7.0
pyarrow                            17.0.0
pyclipper                          1.3.0.post5
pycocotools                        2.0.8
pycodestyle                        2.11.1
pycparser                          2.21
pycryptodomex                      3.20.0
pydantic                           2.8.2
pydantic_core                      2.20.1
pydot                              3.0.1
pyflakes                           3.1.0
pygame                             2.6.0
Pygments                           2.18.0
pylatexenc                         2.10
pylint                             3.2.6
pynvml                             11.5.3
pyparsing                          3.1.2
pypdfium2                          4.30.0
pyproject_hooks                    1.1.0
pyre-extensions                    0.0.30
pysbd                              0.3.4
PySocks                            1.7.1
pytest                             8.3.2
pytest-benchmark                   4.0.0
python-dateutil                    2.9.0
python-doctr                       0.9.0
pytorch-labs-segment-anything-fast 0.2
pytorch-triton                     3.0.0+dedb7bdf33
pytz                               2024.1
PyYAML                             6.0.1
rapidfuzz                          3.9.6
rdflib                             7.0.0
referencing                        0.35.1
regex                              2024.7.24
requests                           2.32.3
resampy                            0.4.3
rfc3986                            1.5.0
rich                               10.9.0
rpds-py                            0.20.0
ruamel.yaml                        0.17.4
ruff                               0.6.0
s3transfer                         0.10.2
safetensors                        0.4.4
scikit-build                       0.18.0
scikit-image                       0.24.0
scikit-learn                       1.5.1
scipy                              1.12.0
segments                           2.2.1
sentencepiece                      0.2.0
sentry-sdk                         2.13.0
setproctitle                       1.3.3
setuptools                         72.1.0
setuptools-git-versioning          2.0.0
shapely                            2.0.6
shellcheck-py                      0.7.2.1
shellingham                        1.5.4
simplejson                         3.19.3
six                                1.16.0
smart-open                         7.0.4
smmap                              5.0.1
sortedcontainers                   2.4.0
soundfile                          0.12.1
soupsieve                          2.6
soxr                               0.4.0
spacy                              3.7.6
spacy-legacy                       3.0.12
spacy-loggers                      1.0.5
srsly                              2.4.8
stdlibs                            2024.5.15
stempeg                            0.2.3
submitit                           1.5.1
sympy                              1.13.1
tabulate                           0.9.0
tensorboard                        2.17.1
tensorboard-data-server            0.7.2
tensorboardX                       2.6.2.2
termcolor                          2.4.0
thinc                              8.2.5
threadpoolctl                      3.5.0
tifffile                           2024.8.10
timm                               0.9.7
tokenizers                         0.19.1
toml                               0.10.2
tomli                              2.0.1
tomlkit                            0.13.2
torch                              2.5.0a0+git4fcd15a /home/yimingzhou/pytorch
torch_geometric                    2.4.0
torchao                            0.4.0
torchaudio                         2.4.0a0+b3f6f51    /home/yimingzhou/torchaudio/src
torchdata                          0.9.0a0+5b7068c
TorchFix                           0.4.0
torchmetrics                       1.0.3
torchmultimodal                    0.1.0b0
torchrec                           0.9.0a0+1306205    /home/yimingzhou/torchrec
torchtext                          0.17.0a0+1d4ce73   /home/yimingzhou/torchtext
torchvision                        0.20.0a0+9e78fe2   /home/yimingzhou/torchvision
tornado                            6.4.1
tqdm                               4.66.5
trailrunner                        1.4.0
transformers                       4.41.0
treetable                          0.2.5
typeguard                          4.3.0
typer                              0.12.4
types-colorama                     0.4.6
types-Jinja2                       2.11.9
types-MarkupSafe                   1.1.10
types-pkg-resources                0.1.3
types-protobuf                     3.19.18
types-PyYAML                       6.0.7
types-requests                     2.27.25
types-tabulate                     0.8.8
types-urllib3                      1.26.25.14
typing_extensions                  4.11.0
typing-inspect                     0.9.0
tzdata                             2024.1
unicodedata2                       15.1.0
Unidecode                          1.3.8
uritemplate                        4.1.1
urllib3                            2.2.2
usort                              1.0.8.post1
visdom                             0.2.4
wandb                              0.17.7
wasabi                             1.1.3
wcwidth                            0.2.13
weasel                             0.4.1
websocket-client                   1.8.0
Werkzeug                           3.0.4
wheel                              0.43.0
wrapt                              1.16.0
xxhash                             3.5.0
xyzservices                        2024.6.0
yacs                               0.1.8
yarl                               1.9.4
zipp                               3.20.0

```

**Comment by FindHao** [comment]
Is this the only model having this issue? If so, the simplest way should be remove this model I think.

**Comment by FindHao** [comment]
Can you try to add a `decoder_start_token_id =None` in here? https://github.com/pytorch/benchmark/blob/e6251f1838701030872e276f94987b7a24a3d6c8/torchbenchmark/util/framework/huggingface/model_factory.py#L162

**Comment by FindHao** [comment]
upstream issue https://github.com/huggingface/transformers/issues/30892

**Comment by yiming0416** [comment]
Opened the issue in HuggingFace transformers repo: https://github.com/huggingface/transformers/issues/33283
